name: Geert Faber
favicon: null
layout_spectrum: 0.50201
typography_spectrum: 0.19583
title: Geert Faber - Media professional working as a strategy and concepts consultant at ComingNext.TV.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.17590469517745078
  lightness: 0.8125
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
